### ISSUE TITLE
Item move up/down buttons

### ISSUE THREAD

**Issue by H1D** [adopted-ember-addons/ember-sortable#153]
Sometimes there is a need for item `[move up]`/`[move down]` buttons. 
For example when item is relatively big comparing to client viewport and D'n'D isn't so easy to do.

I have first dirty attemp ([code](https://github.com/StepicOrg/ember-sortable/compare/master...StepicOrg:item-move-buttons?expand=1)), minimal example:
```handlebars 
{{#sortable-group onChange="reorderItems" as |group|}}
  {{#each model.items as |item|}}
    {{#sortable-item tagName="li" model=item group=group handle=".handle" as |moveUp moveDown|}}
      {{item.name}}
      <span class="handle">&varr;</span>
      <button {{action moveUp}}>&uarr;</button>
      <button {{action moveDown}}>&darr;</button>
    {{/sortable-item}}
  {{/each}}
{{/sortable-group}}
```

Do you need this in upstream? 
What is needed for PR? Tests + docs + demo?

**Comment by jgwhite** [comment]
I like the direction of this. Particularly with an eye towards making it very easy to implement an accessible sortable.

PR with tests+docs+demo would be fab.

One suggestion: rather than the passing these actions as positional params, it might be nice to pass a single hash that can be extended in future.

```hbs
{{#sortable-item ... as |item|}}
  <button onclick={{item.moveUp}}>Up</button>
  <button onclick={{item.moveDown}}>Down</button>
{{/sortable-item}}
```

**Comment by H1D** [comment]
@jgwhite using `{{hash}}` will brake ember <2.3  support. Is it OK?

**Comment by jgwhite** [comment]
@H1D good question.

@cibernox how do you account for availability of the `hash` helper (keyword?) with the ember-power-* projects?

**Comment by H1D** [comment]
@jgwhite nevermind, found [workaround](https://github.com/StepicOrg/ember-sortable/commit/fe46421be7217b652079241bfb89443cb95a3acf#diff-787c16725869a3acd1da4ead0bccf308L1):
```javascript
  _actionsHash: computed(function() {
    return {
      moveUp:  this._move.bind(this, -1),
      moveDown:  this._move.bind(this, +1),
    };
  }),
```
hbs:
```handlebars
{{yield _actionsHash}}
```

**Comment by cibernox** [comment]
@jgwhite A while back I decided to support only Ember 2.3.1+, so I know for sure the hash helper is available. However I have a polyfill and it's very simple: https://github.com/cibernox/ember-hash-helper-polyfill

**Comment by ygongdev** [comment]
Closing as keyboard support is fully built.
