### ISSUE TITLE
Update README with information about maintaining

### ISSUE THREAD

**Issue by jmar910** [adopted-ember-addons/ember-sortable#194]
We should include whatever relevant information that entails. This task can be used to also think about our process for maintaining this repo.

Ideas:
How we at heroku will work on this repo
How to submit PRs
How to submit issues
How to label/annotate submitted issues/prs

**Comment by MelSumner** [comment]
I'm going to close this issue merely due to age. If it's still an issue, please re-open. Thank you! 👍
