### ISSUE TITLE
Please remove sendAction deprecation warning.

### ISSUE THREAD

**Issue by Argun** [adopted-ember-addons/ember-sortable#213]
deprecate.js:102 DEPRECATION: You called sendAction("onChange") but Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action] See https://emberjs.com/deprecations/v3.x#toc_ember-component-send-action for more details.

**Comment by tavosansal** [comment]
There is a couple of usages of `sendAction` in this repo still...would be nice to not have those deprecations anymore. Here is a list: https://github.com/heroku/ember-sortable/search?q=sendAction&unscoped_q=sendAction
