### ISSUE TITLE
Scroll-on-edges is not working when the scroll container is document

### ISSUE THREAD

**Issue by lozjackson** [adopted-ember-addons/ember-sortable#233]
**Describe the bug**
Scroll-on-edges is not working.  When I have a list that overflows the height of the page and the scroll container is the `document` (no internal scrolling), dragging a list item to the top or bottom is not causing the list to scroll.  I have created an ember-twiddle to demonstrate the problem...

**To Reproduce**
1. Go to https://ember-twiddle.com/431624b67579f1a7c25b0675b682c58b?openFiles=templates.application.hbs%2C
2. try to drag a list item to the bottom (or top) edges of the list

**Expected behavior**
The list should scroll to allow dragging the list item to the very bottom, or top of the list

**Additional context**
ember-sortable v1.12.4
This works with 1.12.1

**Comment by jgwhite** [comment]
Thanks for reporting.

**Comment by IgnaceMaes** [comment]
Thanks for bringing this issue up.

It still seems to be present in v1.12.9 still and is preventing an upgrade to any version above v1.12.1 for me.

**Comment by 2468ben** [comment]
Same issue here, broken in v1.12.2-1.12.9 and working great in v1.12.1.

**Comment by romgere** [comment]
Hi ! Any new on this, it seems this issues still exists on 2.1.3.
