### ISSUE TITLE
Element.closest() is unsupported in IE

### ISSUE THREAD

**Issue by samhogg** [adopted-ember-addons/ember-sortable#241]
**Describe the bug**
The use of `Element.closest()` was introduced in #212, causing the `_primeDrag` event to fail on IE 10/11 as the method is unsupported.

**To Reproduce**
1. Open the demo pages in IE10
2. Observe JS errors

**Additional context**
I think this just needs a doc change to call out browser support explicitly, and warning that consumers will need to polyfill in app code.

Happy to raise a PR for this!

**Comment by jgwhite** [comment]
Thanks for the detailed report.

> Happy to raise a PR for this!

Yes please!

**Comment by hornetnz** [comment]
This is also present in IE11. Can you give me some details on how to patch/polyfill this?

**Comment by samhogg** [comment]
@hornetnz - https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

@jgwhite - sorry this got lost in my inbox, raising a PR now.

**Comment by hornetnz** [comment]
Thanks @samhogg. Would it not make more sense to add the polyfill itself into the PR?

**Comment by samhogg** [comment]
@hornetnz discuss over on the PR

**Comment by jgwhite** [comment]
I’ve merged @samhogg’s PR to the README. PRs to either remove Element.closest usage or bake in the polyfill are both welcome.

**Comment by ygongdev** [comment]
PR merged, so I'm closing this.
