### ISSUE TITLE
Reorder is not defined in tests

### ISSUE THREAD

**Issue by mdbiscan** [adopted-ember-addons/ember-sortable#272]
`reorder` is not defined in tests. I followed instructions for adding `import './ember-sortable/test-helpers';` into `/tests/helpers/start-app.js`. I had to create the start-app file. I'm on Ember Version: 3.12. 

Sorry, its not really clear how to make this work.

**Comment by ygongdev** [comment]
I think `3.12` does not use `registerAsyncHelper`, so you can not import `drag` or `reorder` into the `start-app` and expect it to work globally.  Have you tried directly importing it inside the individual test file(s)?

**Comment by mdbiscan** [comment]
I have tried importing it directly in the test, but it did not seem to work or I'm not sure how to add it to hooks? I'm having a hard time finding information on this.

**Comment by ygongdev** [comment]
Yup, I've been trying to rewrite the helpers without breaking their API interface, so you can use them like so.
```
import { reorder } from 'ember-sortable/helpers/reorder;
...

module('reorder test module', function(hooks) {
  setupRenderingTest(hooks);

  test('reorder test', async function(assert) {
  await reorder(....);
  });
});
```
But I'm facing some async issues with making `reorder` working deterministically, so that will take me awhile.

**Comment by ygongdev** [comment]
Closing as change was made in #271 
This will be release with the next `2.0.0` release
