### ISSUE TITLE
1.x to 2.x Migration RFC

### ISSUE THREAD

**Issue by ygongdev** [adopted-ember-addons/ember-sortable#273]
[Rendered](https://github.com/ygongdev/ember-sortable/blob/migration-doc/V2_MIGRATION_RFC.md)
Please review the RFC. Any comments  would be appreciated.
@jgwhite @H1D @chriskrycho @drewlee

**Comment by chriskrycho** [comment]
Thanks for writing it up! For reference, so folks can easily comment inline on it, here's a link to the branch compared against master (which I'll update later if need be): https://github.com/ygongdev/ember-sortable/commit/migration-doc

**Comment by ygongdev** [comment]
Good callout haha.
I created a PR, so we can

**Comment by jgwhite** [comment]
Thanks so much for writing this up. It’s awesome.

I’d encourage you to add a rough release plan to this RFC. Trying to introduce all the features mentioned in the RFC (alongside a good migration story) all in one release sounds too ambitious to me.

i.e.

```md
## 2.0

- New API with backward incompatible changes
- Migration guide

## 2.1

- Built-in keyboard support

## 2.2

- Support for nesting
```

**Comment by ygongdev** [comment]
@jgwhite 

Good idea,  I'll try to break it down into multiple version changes.

**Comment by dbashford** [comment]
Quick question on this... is it possible to get `volatile`/`sendAction` fixes without 2.0 and breaking changes? That in the cards?

**Comment by ygongdev** [comment]
@dbashford I don't have much context on `volatile`, but if the solution is migrate it into native classes, we would also need to bump the `Ember` version to `3.x.x`, which might introduce some other breaking changes, so might as well do it all in one.

Also for `sendAction`, I think that's very do-able, either convert to `this.{actionName}` or use `tryInvoke` if the action might not exist.

@jgwhite @chriskrycho @H1D 
I just added a `release plan` into the `RFC`. If it looks good to you, I think we can get started on 
**2.0**. Although should we  decide on which Ember.version we would to go with?

**Comment by chriskrycho** [comment]
I’ll be reviewing the RFC in detail tomorrow! More thoughts then!

**Comment by ygongdev** [comment]
FYI, I created a new branch `latest-1.x.x` to record the latest backwards compatible master. This is done so we can proceed to active develop on `master` with backwards incompatible changes.
