### ISSUE TITLE
Conflict between Keyboard drag/drop and inputs

### ISSUE THREAD

**Issue by BnitoBzh** [adopted-ember-addons/ember-sortable#308]
If the sortable item contains an input, the space key does not work because the sortable component catch the keyboard event.

When a form element (input element -- all types, select element...) is present in the sortable item, the keys used for the Keyboard drag/drop must NOT be catched by the sortable component (default form behavior must be priorised).

**Comment by ygongdev** [comment]
Thanks for the report, so effectively you have something like the following and the keyboard events on the `input` is also caught on the `item`? Or are you trying to use keyboard on the `item` but also have the event caught by the `input`?
```
{{group.item ...}}
 <input type="text ...>
{{/group.item}}
```

**Comment by ygongdev** [comment]
Feel to re-open if it is still happening after `2.0.2`
