### ISSUE TITLE
Computed .volatile() deprecations

### ISSUE THREAD

**Issue by lukebenimble** [adopted-ember-addons/ember-sortable#310]
Just trying to tidy up my deprecation warnings and currently there are multiple computed property .volatile() warnings emanating from components/sortable-item.

Not a breaking issue at the moment, but will become one eventually - https://deprecations.emberjs.com/v3.x/#toc_computed-property-volatile

Happy to help with this, let me know if you'd like me to submit a PR.

Thanks for the great addon.

**Comment by ygongdev** [comment]
Hey an effort was made in `1.x.x` in #276 
Feel free to tackle this via a PR for `2.x.x`

**Comment by ygongdev** [comment]
Should be handled in `2.0.3` release.
