### ISSUE TITLE
Build error after updating to v2.0.1

### ISSUE THREAD

**Issue by ecoutlee-hortau** [adopted-ember-addons/ember-sortable#311]
**Describe the bug**
I got a build error after updating to v2.0.1. See screenshot below. The app is on Ember 3.12.x (currently updating), node 10.16.3 and use engine with lazy loading.

**To Reproduce**
Update to v2.0.1

**Expected behavior**
Be able to build normally.

**Screenshots**
![build_error](https://user-images.githubusercontent.com/46380280/68230905-04c3e580-ffc8-11e9-8ec8-3fb4856863c0.png)

**Build error log**
[error.dump.8786dc189c858b7410c1bf82676b5ed6.log](https://github.com/adopted-ember-addons/ember-sortable/files/3810389/error.dump.8786dc189c858b7410c1bf82676b5ed6.log)

**Comment by ygongdev** [comment]
Thanks for the report. I'm not quite sure I understand the source of the error.
After a quick search, looks like this might be problem pertaining to `ember-engine`.
https://github.com/ember-engines/ember-engines/issues/400

**Comment by ecoutlee-hortau** [comment]
Thanks for the hint. I will continue to search for a solution. Maybe the issue on ember-engines will help me a little. It's probably related I had a similar issue with ember-tooltips because of ember-engines with lazy loading. No solution has been found yet.

**Comment by ygongdev** [comment]
Closing this for now as it seems to be a problem with `ember-engine`'s lazy loading. Feel free to re-open if it is not the case.

**Comment by ygongdev** [comment]
@ecoutlee-hortau can you check if `2.0.6` mitigates your problem?
Basically I disable the polyfill if your build can't find it. I'll be looking for a long term solution meanwhile

**Comment by ecoutlee-hortau** [comment]
@ygongdev yes `2.0.6` seem to work normally. While looking around about this issue I found this discussion: ember-engines/ember-engines#646. Maybe it will help you to find a solution.

**Comment by ygongdev** [comment]
@ecoutlee-hortau Great find, I'll look into that and see if we can solve this problem permanently.

**Comment by ygongdev** [comment]
@ecoutlee-hortau any update on this? The linked issue seems to have some resolutions.

**Comment by ecoutlee-hortau** [comment]
Good timing @ygongdev. I am currently updating all dependencies of our app. I will have a look at `2.2.1`.

But I didn't have any problem since `2.0.6`. We currently are using  `2.1.4` and it works fine.

I think we could close this issue and open it again if needed.

**Comment by ygongdev** [comment]
Sounds good
