### ISSUE TITLE
Sortable group is not re-render when passed in model is modified

### ISSUE THREAD

**Issue by hingoman25** [adopted-ember-addons/ember-sortable#314]
**Describe the bug**
This isn't a bug but I'm confused about how to implement this addon to my already existing code. Currently, I have a field for phone numbers in which a user can click an add button or a minus button to customize how many phone numbers they want to add to the list. 

The "model" gets updated as the user adds or removes phone numbers. Would anyone here know how to use this addon in a situation like this? I've tried to use it multiple times but haven't been successful in my implementations. I have provided code and screenshots of the app for reference. 

**Screenshots**

![Screen Shot 2019-11-06 at 11 17 30 AM](https://user-images.githubusercontent.com/13734160/68330117-83cc2300-0087-11ea-89b6-e738dc446eae.png)

**Comment by ygongdev** [comment]
Can you show what you've tried? 
I don't exactly understand what you're trying to use it for here

**Comment by hingoman25** [comment]
If a user has multiple phone numbers, I'd like them to be able to drag and reorder them in case they want to change the order later. And when they reorder the phone number, I mean that they can reorder everything within the ul tag which includes the minus button, phone number field, and type dropdown menu.

Here's what I have right now:

![Screen Shot 2019-11-06 at 1 32 55 PM](https://user-images.githubusercontent.com/13734160/68339720-f6de9500-0099-11ea-9b22-b34930640e05.png)

**Comment by ygongdev** [comment]
I see. Can you elaborate what is currently not working? Is the reordered models not being passed currently to `reorderNumbers`?

**Comment by ygongdev** [comment]
Solved as the issue was the dependency was still on `1.2.10`
