### ISSUE TITLE
Cannot reorder without drag icon if we are reordering a text input

### ISSUE THREAD

**Issue by hingoman25** [adopted-ember-addons/ember-sortable#316]
**Describe the bug**
I want to reorder fields that include multiple inputs. The ember-sortable addon does not work with this unless there is an item handle that is specified. 

***Reproduce the bug***
To reproduce this, use the addon on a list of <inputs> and make sure there is no item handle to drag it.

**Comment by ygongdev** [comment]
Are you dragging the `input` directly? or the container that contains the `input`. The first one might have problems.

**Comment by knownasilya** [comment]
Not sure this is a bug, because you should have a handle for accessibility and UX reasons any way.

**Comment by ygongdev** [comment]
Feel to re-open if it is still happening after `2.0.2`
