### ISSUE TITLE
Drag handles should contain button ARIA role

### ISSUE THREAD

**Issue by drewlee** [adopted-ember-addons/ember-sortable#336]
The elements which initiate the accessible sort operation need `role="button"` in order to provide proper context for screen reader and other assistive tech users. Otherwise, users are left unaware that these elements are interactive and actionable.

1. Go to the ember-sortable [demo page](https://adopted-ember-addons.github.io/ember-sortable/demo/).
2. Enable VoiceOver (VO) on a macOS desktop device.
3. Navigate to any of the example lists using Control + Option + Left or Right Arrow keys and focus on a drag handle
4. Note the VoiceOver prompt that announces the element as "text element".

Expected behavior:
When VO is focused on drag handle, the element should be identified as "button."

<img width="1680" alt="Screen Shot 2019-11-25 at 12 19 36 PM" src="https://user-images.githubusercontent.com/945868/69575094-75827000-0f7e-11ea-9799-b917ea3b5661.png">

Likewise, when using the VO rotor (Control + Option + U), the drag handles should appear in the list of Form Controls.

**Comment by ygongdev** [comment]
Thanks Andrew, the fix should be in 828cace905ab7cfda840cc328cfccc17c70833c2
