### ISSUE TITLE
Drag/drop a lot pickier at edges than between items, at least in direction=x

### ISSUE THREAD

**Issue by lupestro** [adopted-ember-addons/ember-sortable#341]
**Describe the bug**
I have a row of from two to five items. Reordering items toward the middle of the row is very smooth and easy. However, moving an item to the edge requires pretty precise placement in order for it to "stick" rather than revert to the original position. 

**To Reproduce**
1. Make a single row of sortable-items that just fit within the sortable-group, perhaps with a small margin (5px?), and no margin between them.
2. Drag items around the middle. It works easily.
2. Drag the middle item to the left edge to sort it. Getting it to take will take several tries.
3. You can accomplish it only if you drop it right at the point where it nearly abuts its neighbor.

**Expected behavior**
If I drag an item to the left, leaving a gap from the (now-shifted) leftmost item, it should reposition cleanly. Likewise on the right.

**Screenshots**
![image](https://user-images.githubusercontent.com/1447893/70664698-e5f4e680-1c38-11ea-9df3-3edf42ef5d8c.png)

**Additional context**
I surmise that it is reverting if the outer edge of the item is outside the parent. It should take the left or right position if any part of the item remains within the parent on that side.

One workaround would be to leave generous padding within the parent. In our case, it is a row of up to five letters (A-E) that are distributed into a fixed space. With five letters, there's just about enough room for a thumbtip over each of them, so the layout is already too tight for padding.

We migrated from ember-drag-drop to ember-sortable today. ember-drag-drop was more forgiving on this score, but ember-sortable looks like it is getting more attention, and hence is likelier to move smoothly into the Octane world (and may work for us in iOS some time soon as well).

**Comment by ygongdev** [comment]
Yeah, I remember something weird on horizontal cases. Can take a deeper look when I have some time. I suspect some calculations might be off

**Comment by ygongdev** [comment]
@lupestro I think this issue is resolved with `2.1.3` can you see if the new release fixes it?

**Comment by lupestro** [comment]
Just checked. Yes - it’s absolutely lovely now.
