### ISSUE TITLE
Sortable items dragged to top, break in container with overflow:auto due to event.clientY = NaN

### ISSUE THREAD

**Issue by validkeys** [adopted-ember-addons/ember-sortable#346]
**Describe the bug**

In the following twiddle [https://ember-twiddle.com/64df3180660c8d3e58830a3d532e5370?openFiles=twiddle.json%2C](https://ember-twiddle.com/64df3180660c8d3e58830a3d532e5370?openFiles=twiddle.json%2C) there is an overflow container containing the scrollable group. You'll notice that dragging any item to the very top and releasing will typically result in the element returning to it's former position

**To Reproduce**
1. Go to [https://ember-twiddle.com/64df3180660c8d3e58830a3d532e5370?openFiles=twiddle.json%2C](https://ember-twiddle.com/64df3180660c8d3e58830a3d532e5370?openFiles=twiddle.json%2C)
2. Drag any item to the top. Unless you hit it exactly right, the dragged element will return to it's initial position on release

**Expected behavior**

When releasing above the first item or outside of the scroll container, it should place the dragged item at the top of the list

**Screenshots**

Not applicable

**Additional context**

In the utils/coordinates "getY" method, if we replace:

```javascript
export function getY(event) {
  let touches = event.changedTouches;
  let touch = touches && touches[0];

  if (touch) {
    return touch.screenY;
  } else {
    return  event.clientY;
  }

```

With

```javascript
export function getY(event) {
  let touches = event.changedTouches;
  let touch = touches && touches[0];

  if (touch) {
    return touch.screenY;
  } else {
    return isNaN(event.clientY) ? event.pageY : event.clientY;
  }
```

All seems to work locally. Will write a PR and am open to any suggestions / feedback

**Comment by ygongdev** [comment]
A PR with a test (if possible) would be greatly appreciated!

**Comment by validkeys** [comment]
Thanks @ygongdev. I'm struggling to create an acceptance test at the moment. The issue I've narrowed down to the "_scrollOnEdges" method in the sortable-item component. It calls drag with a fake event containing only the pageY and pageX properties. I'm going to attempt to use vanilla JS event triggering instead of the triggerEvent ember-test-helper and we'll see how that goes.

**Comment by validkeys** [comment]
Ok I've submitted https://github.com/adopted-ember-addons/ember-sortable/pull/347

**Comment by ygongdev** [comment]
Closing as PR is merged.
