### ISSUE TITLE
Issue in IE11 when reordering ("Object doesn't support property or method 'closest'")

### ISSUE THREAD

**Issue by vigneshk-fd** [adopted-ember-addons/ember-sortable#369]
**Describe the bug**
When reordering is tried in IE11, `Object doesn't support property or method 'closest'` error is thrown in browser console and reorder is not happening in the UI.

**Expected behavior**
Reorder should happen as usual without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/23518504/81289310-d496f580-9083-11ea-8482-b19428152e9c.png)
**Windows 10**
**Internet Explorer v11**.1.17134.0

**Analysis**:
The issue happens in the` addon/components/sortable-item.js` file `_primeDrag` method : 
`startEvent.target.closest` is **undefined** in this case.

![image](https://user-images.githubusercontent.com/23518504/81292713-b7fdbc00-9089-11ea-91cb-f386097401f7.png)

**Comment by ygongdev** [comment]
This is stated in the readme. For some reason, the polyfill for closest that is included with `ember-sortable` does not work for some production apps. Therefore you would need to include your own polyfill.

**Comment by vigneshk-fd** [comment]
Adding polyfill for the `closest` method in the vendor folder, worked. Thanks @ygongdev. Closing the issue.
