### ISSUE TITLE
Dragged item moves back

### ISSUE THREAD

**Issue by aandis** [adopted-ember-addons/ember-sortable#381]
**Describe the bug**
When dragging items, sometimes they move back to their original location. The bug occurs intermittently and I see this with `direction = x`, on left movements.

**To Reproduce**
I've tried reproducing this on a simpler twiddle but haven't been able to yet. However, I did create this gif which demonstrates the issue I'm having - 

![bug](https://user-images.githubusercontent.com/4983347/89716956-1a3ec380-d9cf-11ea-9a40-cc220dcdc14b.gif)

**Additional context**
Ember - 3.4.4
Ember Sortable - 2.1.1

**Comment by aandis** [comment]
I'm not quite sure if this is a bug in the lib or not since I haven't been able to reproduce it but if you have any pointers on what can cause this, it would be a huge help.

**Comment by aandis** [comment]
I tracked the `onChange` method and it looks like it's being called with the original list of items instead of the reordered list which is why the item moves back. Not sure why though.

**Comment by aandis** [comment]
I see this only occurs when the edge elements are involved and the item being dragged moves out of list boundaries. Might be related to https://github.com/adopted-ember-addons/ember-sortable/issues/72

**Comment by ygongdev** [comment]
@aandis Can you bump to `2.1.3`? I think this might be fixed by #347

**Comment by aandis** [comment]
Works perfect. Thank you!
