### ISSUE TITLE
sortable-group modifier throws error during destruction

### ISSUE THREAD

**Issue by mhankus** [adopted-ember-addons/ember-sortable#398]
I have sortable-group modifier used inside of other component. I'm using ember 3.22. When component with sortable-group inside is removed from dom, error is thrown in willRemove at line 
```
      this.announcer.parentNode.removeChild(this.announcer);
```
because this.announcer.parentNode is null;

I suspect, that problem is that this sortable group modifier adds this announcer element as its adjacent element, so it manages context outside of its responsibility (I assume that modifier is allowed to manage only itself and its children, but this announcer element is sibling to this sortable-group, so it can be removed by some other task, before willRemove is called).

I have performed test, and set breakpoints on:
1. willRemove 
2. in dom on this announcer element removal

Browser (latest chrome), stopped on "dom node removal" breakpoint first, then in "willRemove" function.

As a quick fix you, before calling removeChild, you can check if parentNode is null. (I would appreciate such fix, because 2.1.4 fails with ember 3.22, and 2.2 also fails due to this modifier bug).

**Comment by cah-briangantzler** [comment]
When you say inside, do you mean the sortable group is in the components template, or that the sortable group is used in the components block template (that part between <comp></comp>)

Attempting to setup a failing test.

**Comment by mhankus** [comment]
I'm using sortable group inside if helper code looks like
```
{{#if this.someCondition}}
<ul {{sortable-group ......}}>

 rest of the code
</ul> 
{{/if}}
```
When someCondition is changed to false, error is thrown.
I've noticed that there is already pull request which fixes this problem exactly as I proposed https://github.com/adopted-ember-addons/ember-sortable/pull/374  but there is no tests for this problem.
