### ISSUE TITLE
Sortable group is not re-render after sorting rows, and model is then updated then after

### ISSUE THREAD

**Issue by anandlall112** [adopted-ember-addons/ember-sortable#410]
Having a weird bug as to where sortable is not re-rendering the list when model data is updated AFTER reordering items. 
Note: it works if model data is updated without previously reordering the list

Ember: 3.24.1
Sortable: 2.2.2

Steps to follow reproduce:
1. Render a list of items
2. Sort the list of items
3. push another object to the model data array - Notice sortable did not re-render the list

Any idea on how to solve this?

**Comment by ygongdev** [comment]
Hard to tell without any more context, have you re-initialized the model data array with the new reordered array in step 2?
```js
    reorderItems(groupModel, itemModels, draggedModel) {
      groupModel.set('items', itemModels); // re-initialize
    }
```

**Comment by anandlall112** [comment]
Hi ygongdev, i am using it without groupModel. This is reordering fine. But if reordering then appending data then after is the issue

```
  <SortableGroup
    @tagName="div"
    @model={{this.fields}}
    @onChange={{action this.reorderItems}} as |group|>
    {{#each group.model as |field|}}
      <group.item
        @tagName="div"
        @model={{field}} as |sbitem|>
        <Ui::Form @field={{field}}>
          <sbitem.handle>
            {{inline-svg "move" class="drag-handle"}}
          </sbitem.handle>
        </Ui::Form>
      </group.item>
    {{/each}}
  </SortableGroup>
```

```
import Component from '@glimmer/component';
import {tracked} from '@glimmer/tracking';
import {action, set} from "@ember/object";

export default class UiFormComponent extends Component {
  
  @tracked fields;

  constructor() {
    super(...arguments);
    this.fields = this.args.fields;
  }

  @action
  reorderItems(fields, selected) {
    set(this, 'fields', fields);
  }
}
```

**Comment by ygongdev** [comment]
I don't think I see `reordering then appending data then after is the issue` in the snippet you shared?
Where are you appending data? `this.fields` or `this.args.fields`?

**Comment by anandlall112** [comment]
The field is being appended to this.fields

```
  @action
  onAddField(element) {
    let field = {...this.defaultFields[element.type]};
    this.fields.pushObject(field);
  }
```

Another thing i want to point out to confirm that appending is working fine. If i push a field without "reordering", appending works fine. The new field is appended at the bottom of the list.

However, if i re-order the list "then after" push an object to the list the new item is not added to the list.
On this point, If i log {{log this.fields}} in hbs, i see it is updating with the newly added object but sortable is not rendering it

**Comment by ygongdev** [comment]
I see. I'm actually not sure if `pushObject` works well with `@tracked`.

The elements in `this.fields` are usually not autotracked.

For example, if `this.fields` was a native array, e.g `[]`, I would do the following to re-initialize `this.fields` in `onAddField` to properly propagate the change to trigger `@tracked` on `this.fields`:
```js
  @action
  onAddField(element) {
    let field = {...this.defaultFields[element.type]};
    this.fields = [...this.fields, field]
  }
  ```

**Comment by anandlall112** [comment]
We used tracked here for another purpose. The component is pretty fat so i had to slim it down to give you some context here. I removed the @tracked and tried it as well, same result. But as i mentioned, in console i can see that the this.fields list is updating in the template, its just not being re-rendered. 
The application we are building is very large and confidential so i am not able to post any links here, however i can send you an email with a link to a test build so you can see what is happening. Let me know if you are ok with that

**Comment by ygongdev** [comment]
Oh we don't need to do all that.
The key to re-render the sortable-group is `@model`. 
The elements in `this.fields` can be updated correctly, but unless you re-init or reassign the reference of `this.fields`. The sortable-group will not update because it reacts to change only on `this.fields`, not on its children.

I think this should work:
```
  @tracked fields = this.args.fields
  
  @action
  onAddField(element) {
    let field = {...this.defaultFields[element.type]};
    this.fields = [...this.fields, field]
  }
  ```

**Comment by cah-briangantzler** [comment]
@tracked for arrays does not track content of the array, they expect the array to be immutable, ie you do not add an element to array you create a new array copy, add item, then assign that. (Yes you could add the element to the existing array and then assign the array again, but you end up with myArray = myArray line and that looks suspect). @tracked also does not work as computed, in that computed will not trigger if the same value is assigned where as @tracked triggers if a value is assigned, it does not check that it is the same which is why myArray = myArray triggers the @tracked.

You can also look a this https://github.com/pzuraq/tracked-built-ins

**Comment by anandlall112** [comment]
Thank you guys for helping me finding the root to this issue. The problem was hard to find because there are 3 different components connected to each other. The issue was we were updating the `this.fields` which would not update the model

to solve this issue after re-ordering, we cleared all the items inside the model and push the updated records back. We are then able to append with `pushObject` as before

```
  @action
  reorderItems(fields, selected) {
    this.args.fields.setObjects([]);
    this.args.fields.pushObjects(fields);
  }
```

**Comment by ygongdev** [comment]
Good to know! May I close the issue? @anandlall112

**Comment by anandlall112** [comment]
Yep. all good here :)
