### ISSUE TITLE
Set aria-grabbed on sortable-item when item is grabbed

### ISSUE THREAD

**Issue by knownasilya** [adopted-ember-addons/ember-sortable#414]
https://www.w3.org/TR/2011/CR-wai-aria-20110118/states_and_properties#aria-grabbed

This seems generic enough that it would make sense to be implemented here. Since it affects accessibility for everyone.

Also https://www.w3.org/TR/2011/CR-wai-aria-20110118/states_and_properties#aria-dropeffect should be set on the sortable group or maybe just documented that it should be set, since it's not dynamic.

**Comment by ZoeBijl** [comment]
Both of these attributes have been [deprecated in ARIA 1.1](https://www.w3.org/TR/wai-aria-1.1/#attrs_dragdrop).

**Comment by MelSumner** [comment]
Closing since these are deprecated. 👍
