### ISSUE TITLE
Multiple ember-sortable groups references wrong / last iterator in loop

### ISSUE THREAD

**Issue by jeroenweareorangeeu** [adopted-ember-addons/ember-sortable#422]
Hello all,

I am using the Ember-sortable addon for sorting Questions.
I have a ReportTemplate with multiple Sections which has multiple Questions. The Questions (at this point) need to be Sortable.
I use a Bootstrap 4 List Group to show the Sections; clicking on a Section show the underlying question which can be be sorted.
(https://getbootstrap.com/docs/4.0/components/list-group/)

I am looping through the Sections and  Questions to display them.
I am using a Ember Component based setup, iterating through components.

The rendering / displaying of the Sections and Question is correct, however when I drag a Question to be sorted, I then recieve the wrong Section in my 'reOrderQuestion' function.  My 'this.args.section' is the LAST section in the section list, always.
Also the Question themselves are 1 big pile of Questions, instead of the two seperate Questions for just this Section.

In this example I have 4 Sections: Section 1 - 4.
Section 1 ha two Questions, 1 and 2
Section 2 has two Question 3 and 4
Section 3 and 4 have no Questions.

**To Reproduce**
Steps to reproduce the behavior: as described before

**Expected behavior**
I expect Ember-Sortable to have the correct Section reference, not the last one.
I need this so I can change new sortation of Question to the right Section and save the ReportTemplate.
Also I need to receive the right Questions for the Sections, not ALL the Question in the entire ReportTemplate.

**Screenshots**
Screenshots added.

**Additional context**
Using Ember 3.26 and Embers-sortable 2.2.3.
The Model for Reporttemplate defined in Ember is only the 'Sections' array. The Sections and Question are not modeled; this is just data in a JSON structure which is put there by the back-end. See screenshot and comment with JSON structure.

Any help / light shedded on this issue would be appreciated!
Any questions or remarks are welcome!

Greetings,

Jeroen Baartmans

**Comment by jeroenweareorangeeu** [comment]
#
![code_question js](https://user-images.githubusercontent.com/83004496/119783662-b8076e80-becd-11eb-9298-b589329915fd.png)
![code_section hbs](https://user-images.githubusercontent.com/83004496/119783664-b8a00500-becd-11eb-91f9-aee91e784973.png)
![code_section-detail hbs](https://user-images.githubusercontent.com/83004496/119783668-b9389b80-becd-11eb-9328-d9672bde134b.png)
![section_1_debug_output_after_drag](https://user-images.githubusercontent.com/83004496/119783670-b9389b80-becd-11eb-8bc9-993cc84e694a.png)
![section_1_overview](https://user-images.githubusercontent.com/83004496/119783673-b9d13200-becd-11eb-8e9a-10f3c9bd8aba.png)
![section_2_overview](https://user-images.githubusercontent.com/83004496/119783674-b9d13200-becd-11eb-8439-1b769c943225.png)
![section_4_overview](https://user-images.githubusercontent.com/83004496/119783676-b9d13200-becd-11eb-9054-51595473cd58.png)
![code_question hbs](https://user-images.githubusercontent.com/83004496/119783677-ba69c880-becd-11eb-9f49-81bf6249b0d8.png)

**Comment by jeroenweareorangeeu** [comment]
Reporttemplate Model

![code_reporttemplate_model](https://user-images.githubusercontent.com/83004496/119785048-21d44800-becf-11eb-96a4-9dde634687a2.png)

**Comment by jeroenweareorangeeu** [comment]
`{
   "content":"<p>TEST</p>",
   "icon":{
      
   },
   "sections":[
      {
         "id":"562b65d5-1be4-4048-b9ff-a76e23c79731",
         "title":"Section #1",
         "questions":[
            {
               "id":"2",
               "title":"Question #2"
            },
            {
               "id":"1",
               "title":"Question #1"
            }
         ]
      },
      {
         "id":"29248d1b-4269-4d9f-a18b-c9a7efa9cd54",
         "title":"Section #2",
         "questions":[
            {
               "id":"3",
               "title":"Question #3"
            },
            {
               "id":"4",
               "title":"Question #4"
            }
         ]
      },
      {
         "id":"8ff30706-3322-4e67-bef6-0acfa70fc8ea",
         "title":"Section #3"
      },
      {
         "id":"2c784ec6-ca6c-4314-a860-f2aa426c1021",
         "title":"Section #4"
      }
   ],
   "title":"Test 2"
}`

**Comment by jeroenweareorangeeu** [comment]
I might have made a mistake with name-ing the 'groupName'; they are all the same. I think I found a solution for this. Will need to investigate further. Tomorrow I will give an update.

**Comment by cah-briangantzler** [comment]
I have not really understood the group name property. The same thing could have been accomplished by currying a parameter in the action that is passed in. Ember sortable just stores it and echos it back, it doesnt actually use it.   I have wanted to remove it as part of the re-write to modifiers but was asked to leave it in so as not to make a breaking change.   But as I understand the group property, its really not an ember-sortable concern.

I hadnt gotten around to looking at your code yet, but I had suspected that you thought group name have worked like name on radio buttons which it does not.  Glad you found that out yourself.

**Comment by jeroenweareorangeeu** [comment]
As I sais yesterday, I made mistake with the groupName attribute, which wasnt unique. This is not an isssue in Ember-Sortable, just in the way I've set things up. I will now close the ticket, because it is not relevant anymore.
