### ISSUE TITLE
Deprecation use of "run.schedule" and "run.next"

### ISSUE THREAD

**Issue by makannew** [adopted-ember-addons/ember-sortable#436]
Deprecation warnings displayed on console while dragging a row.

"DEPRECATION: Using `run.schedule` has been deprecated. Instead, import the value directly from @ember/runloop:"

"DEPRECATION: Using `run.next` has been deprecated. Instead, import the value directly from @ember/runloop:"

**Comment by snewcomer** [comment]
closed by https://github.com/adopted-ember-addons/ember-sortable/pull/445

**Comment by MelSumner** [comment]
Closing this issue as it was resolved by #445
