### ISSUE TITLE
Horizontal sorting seems broken in version 3.0.0

### ISSUE THREAD

**Issue by killianguilland** [adopted-ember-addons/ember-sortable#454]
**Describe the bug**
When dragging an item to the left, other items further left do not move at all.
When dragging the item to right, other items move, but not the one currently being dragged. 

This only happens with horizontal sorting, vertical sorting seems to be working fine.

This issue is kind of hard to explain so here is an example of what I mean : 
https://ember-twiddle.com/714cb368691a7ff9e1fb9d8a8ee8d4a2?openFiles=templates.application%5C.hbs%2C

**To Reproduce**

Try dragging an item left of right.

**Additional context**

Downgrading to 2.4.0 (which I believe was the latest version before 3.0.0 ?) has solved the issue for me.
Since 3.0.0 has been released only a few days ago, maybe this bug went under the radar ?

Sorry if this issue is unclear, English is not my first language 😄 let me know if you need any more information !

**Comment by robinborst95** [comment]
@snewcomer seems like https://github.com/adopted-ember-addons/ember-sortable/pull/452/commits/daf5a0124f84be90b8788d1fc7a02feaf01503fe#diff-8e3a9c4ee872896b6316a006064edab4463ec84004f745ae119f5ca7273f6685R573 causes the issue. In our app we experience the same issue and if we downgrade to 2.4.0 and inspect the elements, the 'next' elements have a negative `translateX` value:

![image](https://user-images.githubusercontent.com/5949434/146372767-e9a04ef2-d643-4aad-a523-e57ca8a062c8.png)
