### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by fpauser** [adopted-ember-addons/ember-sortable#457]
Would be great to have the updated `ember-test-selectors` (#446) released...

**Comment by MelSumner** [comment]
cc @adopted-ember-addons/admin let's try to get a release out for this soon.

**Comment by rwwagner90** [comment]
Looks like I don't have permissions on npm for this repo, but a lot of folks do.

**Comment by fpauser** [comment]
Any news on this?

**Comment by NullVoxPopuli** [comment]
I'll bother the folks in Discord

**Comment by knownasilya** [comment]
v3.0.1 should be out
