### ISSUE TITLE
Modifiers: using this.args is deprecated

### ISSUE THREAD

**Issue by edflips** [adopted-ember-addons/ember-sortable#483]
**Describe the bug**
We are seeing multiple deprecation warnings running:

 - `ember-sortable 2.2.3`
 - `Ember 4.4.0`
 - `ember-modifier 3.2.7`

```
using this.args is deprecated. Access positional and named arguments directly in the modify hook instead. [deprecation id: ember-modifier.no-args-property] This will be removed in Ember 4.0.0.
```

**To Reproduce**

1. Install the above packages
2. Implement a sortable list
4. Observe the modifier warnings

**Expected behavior**
No warnings

**Comment by NullVoxPopuli** [comment]
Does the same happen with ember-sortable v4?

**Comment by barryofguilder** [comment]
@NullVoxPopuli I just installed v4 in my Ember 4.6 project and I'm seeing the modifier deprecation warnings.

**Comment by NullVoxPopuli** [comment]
makes sense -- I don't think anyone has submitted a PR to clean those up

**Comment by kaermorchen** [comment]
I have caught this deprecation too.

ember-source@4.6.0
ember-sortable@4.0.0

Look like #487 should resolve this issue.
