### ISSUE TITLE
using sortable-item and sortable-handle

### ISSUE THREAD

**Issue by st-h** [adopted-ember-addons/ember-sortable#486]
I would like to use the whole sortable-item as a sortable-handle, so it does not matter where on the element the click happens. However, when I try to apply both modifiers to the same Dom element, the items are not sortable at all. Clicking and dragging does nothing. 
In order to fix this, I need to create a wrapper like:

```
<div {{sortable-item}} class="wrapper>
  <div {{sortable-handle}} class="content">
    actual content...
  </div>
</div>
```

It would be great if we could just apply both modifiers to the same element, so that it is not necessary to create an additional wrapper to make is addon work:

```
<div {{sortable-item}} {{sortable-handle}} class="wrapper>
    actual content...
</div>
```

**Comment by bertdeblock** [comment]
FWIW, we're applying both modifiers to the same element and everything seems to work fine.

**Comment by st-h** [comment]
@bertdeblock thanks for your comment. I have given this another try. Strangely, I can not reproduce the issues I saw in the past. The only issue I see is that the `touch-action: none` css style prevents scrolling on iOS devices when sortable is disabled. I'll open a new issue for that.
